name: DinD Compose Test

on:
  push:
    branches: [main]

jobs:
  docker-in-docker:
    runs-on: ubuntu-latest

    container:
      image: docker:24.0.7-cli  # or your preferred stable docker version
      options: --privileged     # Required for DinD to work
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and run containers
        run: docker compose up --build go-app

      - name: Check Go app logs
        run: docker-compose logs go-app

      - name: Describe the created table
        run: docker run --rm --network container:$(docker compose ps -q db) postgres:16 psql "postgresql://testuser:testpass@localhost:5432/testdb" -c '\d hello'

      - name: Tear down
        if: always()
        run: docker-compose down
